### ISSUE TITLE
NullPointerException after calling localhost:9000/c3po

### ISSUE THREAD

**Issue by stiefel40k** [datascience/c3po#41]
Hi,

i tried both running `activator start` as well as building the binaries with `activator clean compile stage`. The server starts and it is waiting for connections, and the mongodb also recognizes the connection from the server. But as soon as I go to localhost:9000/c3po I get the following exception:

```
2016-04-25 10:34:18,566 - [DEBUG] [application]: Received an index call in application
2016-04-25 10:34:18,570 - [DEBUG] [application]: Building a new session with id:'null'
2016-04-25 10:34:18,580 - [DEBUG] [application]: Listing collection names
2016-04-25 10:34:18,595 - [ERROR] [play]: Cannot invoke the action, eventually got an error: java.lang.NullPointerException
2016-04-25 10:34:18,639 - [ERROR] [application]: 

! @6pp7knd6e - Internal server error, for (GET) [/c3po] ->

play.api.Application$$anon$1: Execution exception[[NullPointerException: null]]
	at play.api.Application$class.handleError(Application.scala:296) ~[com.typesafe.play.play_2.11-2.3.0.jar:2.3.0]
	at play.api.DefaultApplication.handleError(Application.scala:402) [com.typesafe.play.play_2.11-2.3.0.jar:2.3.0]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$4.apply(PlayDefaultUpstreamHandler.scala:320) [com.typesafe.play.play_2.11-2.3.0.jar:2.3.0]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$4.apply(PlayDefaultUpstreamHandler.scala:320) [com.typesafe.play.play_2.11-2.3.0.jar:2.3.0]
	at scala.Option.map(Option.scala:145) [org.scala-lang.scala-library-2.11.1.jar:na]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3.applyOrElse(PlayDefaultUpstreamHandler.scala:320) [com.typesafe.play.play_2.11-2.3.0.jar:2.3.0]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3.applyOrElse(PlayDefaultUpstreamHandler.scala:316) [com.typesafe.play.play_2.11-2.3.0.jar:2.3.0]
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:344) [org.scala-lang.scala-library-2.11.1.jar:na]
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:343) [org.scala-lang.scala-library-2.11.1.jar:na]
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32) [org.scala-lang.scala-library-2.11.1.jar:na]
	at play.api.libs.iteratee.Execution$trampoline$.execute(Execution.scala:46) [com.typesafe.play.play-iteratees_2.11-2.3.0.jar:2.3.0]
	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:40) [org.scala-lang.scala-library-2.11.1.jar:na]
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:248) [org.scala-lang.scala-library-2.11.1.jar:na]
	at scala.concurrent.Promise$class.complete(Promise.scala:55) [org.scala-lang.scala-library-2.11.1.jar:na]
	at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:153) [org.scala-lang.scala-library-2.11.1.jar:na]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:23) [org.scala-lang.scala-library-2.11.1.jar:na]
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:41) [com.typesafe.akka.akka-actor_2.11-2.3.3.jar:na]
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:393) [com.typesafe.akka.akka-actor_2.11-2.3.3.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [org.scala-lang.scala-library-2.11.1.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [org.scala-lang.scala-library-2.11.1.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [org.scala-lang.scala-library-2.11.1.jar:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [org.scala-lang.scala-library-2.11.1.jar:na]
Caused by: java.lang.NullPointerException: null
	at com.petpet.c3po.dao.mongo.MongoPersistenceLayer.distinct(MongoPersistenceLayer.java:467) ~[c3po-core-0.5.0.jar:na]
	at com.petpet.c3po.dao.DefaultPersistenceLayer.distinct(DefaultPersistenceLayer.java:114) ~[c3po-core-0.5.0.jar:na]
	at controllers.Properties.getCollectionNames(Properties.java:58) ~[c3po.c3po-0.4.0.jar:0.4.0]
	at controllers.Application.index(Application.java:63) ~[c3po.c3po-0.4.0.jar:0.4.0]
	at Routes$$anonfun$routes$1$$anonfun$applyOrElse$2$$anonfun$apply$2.apply(routes_routing.scala:243) ~[c3po.c3po-0.4.0.jar:na]
	at Routes$$anonfun$routes$1$$anonfun$applyOrElse$2$$anonfun$apply$2.apply(routes_routing.scala:243) ~[c3po.c3po-0.4.0.jar:na]
	at play.core.Router$HandlerInvokerFactory$$anon$4.resultCall(Router.scala:264) ~[com.typesafe.play.play_2.11-2.3.0.jar:2.3.0]
	at play.core.Router$HandlerInvokerFactory$JavaActionInvokerFactory$$anon$15$$anon$1.invocation(Router.scala:255) ~[com.typesafe.play.play_2.11-2.3.0.jar:2.3.0]
	at play.core.j.JavaAction$$anon$1.call(JavaAction.scala:55) ~[com.typesafe.play.play_2.11-2.3.0.jar:2.3.0]
	at play.GlobalSettings$1.call(GlobalSettings.java:67) ~[com.typesafe.play.play_2.11-2.3.0.jar:2.3.0]
	at play.core.j.JavaAction$$anonfun$11.apply(JavaAction.scala:82) ~[com.typesafe.play.play_2.11-2.3.0.jar:2.3.0]
	at play.core.j.JavaAction$$anonfun$11.apply(JavaAction.scala:82) ~[com.typesafe.play.play_2.11-2.3.0.jar:2.3.0]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) [org.scala-lang.scala-library-2.11.1.jar:na]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) [org.scala-lang.scala-library-2.11.1.jar:na]
	at play.core.j.HttpExecutionContext$$anon$2.run(HttpExecutionContext.scala:40) ~[com.typesafe.play.play_2.11-2.3.0.jar:2.3.0]
	at play.api.libs.iteratee.Execution$trampoline$.execute(Execution.scala:46) [com.typesafe.play.play-iteratees_2.11-2.3.0.jar:2.3.0]
	at play.core.j.HttpExecutionContext.execute(HttpExecutionContext.scala:32) ~[com.typesafe.play.play_2.11-2.3.0.jar:2.3.0]
	at scala.concurrent.impl.Future$.apply(Future.scala:31) ~[org.scala-lang.scala-library-2.11.1.jar:na]
	at scala.concurrent.Future$.apply(Future.scala:492) ~[org.scala-lang.scala-library-2.11.1.jar:na]
	at play.core.j.JavaAction$class.apply(JavaAction.scala:82) ~[com.typesafe.play.play_2.11-2.3.0.jar:2.3.0]
	at play.core.Router$HandlerInvokerFactory$JavaActionInvokerFactory$$anon$15$$anon$1.apply(Router.scala:252) ~[com.typesafe.play.play_2.11-2.3.0.jar:2.3.0]
	at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4$$anonfun$apply$5.apply(Action.scala:130) ~[com.typesafe.play.play_2.11-2.3.0.jar:2.3.0]
	at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4$$anonfun$apply$5.apply(Action.scala:130) ~[com.typesafe.play.play_2.11-2.3.0.jar:2.3.0]
	at play.utils.Threads$.withContextClassLoader(Threads.scala:21) ~[com.typesafe.play.play_2.11-2.3.0.jar:2.3.0]
	at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4.apply(Action.scala:129) ~[com.typesafe.play.play_2.11-2.3.0.jar:2.3.0]
	at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4.apply(Action.scala:128) ~[com.typesafe.play.play_2.11-2.3.0.jar:2.3.0]
	at scala.Option.map(Option.scala:145) [org.scala-lang.scala-library-2.11.1.jar:na]
	at play.api.mvc.Action$$anonfun$apply$1.apply(Action.scala:128) ~[com.typesafe.play.play_2.11-2.3.0.jar:2.3.0]
	at play.api.mvc.Action$$anonfun$apply$1.apply(Action.scala:121) ~[com.typesafe.play.play_2.11-2.3.0.jar:2.3.0]
	at play.api.libs.iteratee.Iteratee$$anonfun$mapM$1.apply(Iteratee.scala:483) ~[com.typesafe.play.play-iteratees_2.11-2.3.0.jar:2.3.0]
	at play.api.libs.iteratee.Iteratee$$anonfun$mapM$1.apply(Iteratee.scala:483) ~[com.typesafe.play.play-iteratees_2.11-2.3.0.jar:2.3.0]
	at play.api.libs.iteratee.Iteratee$$anonfun$flatMapM$1.apply(Iteratee.scala:519) ~[com.typesafe.play.play-iteratees_2.11-2.3.0.jar:2.3.0]
	at play.api.libs.iteratee.Iteratee$$anonfun$flatMapM$1.apply(Iteratee.scala:519) ~[com.typesafe.play.play-iteratees_2.11-2.3.0.jar:2.3.0]
	at play.api.libs.iteratee.Iteratee$$anonfun$flatMap$1$$anonfun$apply$14.apply(Iteratee.scala:496) ~[com.typesafe.play.play-iteratees_2.11-2.3.0.jar:2.3.0]
	at play.api.libs.iteratee.Iteratee$$anonfun$flatMap$1$$anonfun$apply$14.apply(Iteratee.scala:496) ~[com.typesafe.play.play-iteratees_2.11-2.3.0.jar:2.3.0]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) [org.scala-lang.scala-library-2.11.1.jar:na]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) [org.scala-lang.scala-library-2.11.1.jar:na]
	... 6 common frames omitted
```

I am using the newest (1.3.10) version of activator with java 8 and mongodb 2.6.10

**Comment by artourkin** [comment]
Hi, thank you for reporting the issue. Which OS do you use?

**Comment by stiefel40k** [comment]
Ubuntu 15.10 (as a virtual machine)

**Comment by artourkin** [comment]
Did you use c3po-cmd to load data in mongodb? Does mongodb contain anything?

**Comment by stiefel40k** [comment]
Yes. I was able to deploy this WAR on a tomcat server (on the same machine): http://dl.bintray.com/peshkira/c3po/ which is able to show the data imported into the database (with some other bugs, but it is irrelevant)

**Comment by artourkin** [comment]
The binaries (war and jar) from your link are from the older version of c3po. If you still want to use that version, you should refer to the corresponding usage guide: https://github.com/peshkira/c3po/wiki/Usage-Guide. To compile this, you should use Play Framework 2.0.4.

The latest version of C3PO (cmd-0.5 and web-0.4) is based on Play Framework 2.3.0 and is more stable.

**Comment by stiefel40k** [comment]
Yes I know. I want to use this version. I only refered to that version to verify, that there is data in the database. Still the error I presented is in THIS version.

**Comment by artourkin** [comment]
I have just tried the installation procedure with Java versions 1.7, 1.8 and MongoDB versions 2.4.9, 3.2 on Ubuntu 15. It works fine and I cannot reproduce this exception. The app should work even for an empty database.

**Comment by stiefel40k** [comment]
I set up a new machine, and configured everything manually, and now I was able to start the application, and it is running smoothly (except the plato export...there I get a ClassCastException Sting can't be cast to Number). I have no idea what was the problem actually. But the thing is it is running now. Thanks anyway for the help. (Should I open a new case for the CastException?)

**Comment by artourkin** [comment]
Yes please.
