### ISSUE TITLE
NullPointer Exception on Content Profile download

### ISSUE THREAD

**Issue by ksmolikova** [datascience/c3po#43]
When I try to export xml I get this error:
`Caused by: java.lang.NullPointerException: null
	at org.bson.BasicBSONObject.getDouble(BasicBSONObject.java:154) ~[org.mongodb.mongo-java-driver-2.7.2.jar:na]
	at com.petpet.c3po.dao.mongo.MongoPersistenceLayer.parseNumericStatistics(MongoPersistenceLayer.java:701) ~[c3po-core-0.5.0.jar:na]
	at com.petpet.c3po.dao.mongo.MongoPersistenceLayer.getNumericStatistics(MongoPersistenceLayer.java:541) ~[c3po-core-0.5.0.jar:na]
	at com.petpet.c3po.dao.DefaultPersistenceLayer.getNumericStatistics(DefaultPersistenceLayer.java:130) ~[c3po-core-0.5.0.jar:na]
	at com.petpet.c3po.analysis.ProfileGenerator.processNumericProperty(ProfileGenerator.java:396) ~[c3po-core-0.5.0.jar:na]
	at com.petpet.c3po.analysis.ProfileGenerator.createPropertyElement(ProfileGenerator.java:289) ~[c3po-core-0.5.0.jar:na]
	at com.petpet.c3po.analysis.ProfileGenerator.generateProperties(ProfileGenerator.java:261) ~[c3po-core-0.5.0.jar:na]
	at com.petpet.c3po.analysis.ProfileGenerator.generateProfile(ProfileGenerator.java:191) ~[c3po-core-0.5.0.jar:na]
	at com.petpet.c3po.analysis.ProfileGenerator.generateProfile(ProfileGenerator.java:163) ~[c3po-core-0.5.0.jar:na]
	at controllers.Export.generateProfile(Export.java:160) ~[c3po.c3po-0.4.0.jar:0.4.0]
	at controllers.Export.profileAsXml(Export.java:140) ~[c3po.c3po-0.4.0.jar:0.4.0]`

**Comment by artourkin** [comment]
This one is resolved. I never thought a null value is possible for a map-reduce result.

**Comment by artourkin** [comment]
Could please confirm if the issue is resolved?

**Comment by ksmolikova** [comment]
Of course. Thank you.
